version: 0.2 

phases: 
  install: 
    commands: 
      - java -version 
      - gradle -v 
  build: 
    commands: 
      - gradle clean
      - gradle assemble
      - gradle test
      - gradle build