version: 0.2 
batch:
  build-matrix:
    static:
      ignore-failure: false
      env:
        type: LINUX_CONTAINER
        privileged-mode: true
    dynamic:
      env:
        image:
          - aws/codebuild/amazonlinux2-x86_64-standard:3.0
          ## - aws/codebuild/windows-base:2.0
        variables:
          MY_VAR:
            - java_test.AppTest
            - VALUE2
            - VALUE3

phases: 
  install: 
    commands: 
      - java -version 
      - gradle -v 
  build: 
    commands: 
      - echo "yeah------"
      - echo $MY_VAR
      - gradle clean
      - gradle assemble
      #- gradle test
      - gradle test --tests="$MY_VAR"
      #- gradle build