/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java_test;

import org.junit.Test;
import static org.junit.Assert.*;

import javax.lang.model.type.NullType;

public class AppTest2 {
    @Test
    public void testAppHasAGreeting2_1() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test
    public void testNull2_1() {
        App classUnderTest = new App();
        assertNotNull("NotNull", "test");
    }

    @Test
    public void testNull2_2() {
        App classUnderTest = new App();
        assertNotNull("NotNull", "test");
    }
}
